# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: svogrig <svogrig@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/22 03:03:35 by svogrig           #+#    #+#              #
#    Updated: 2025/03/04 01:39:35 by svogrig          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	:=	animal

SRC 	:=	main.cpp \
			Animal.cpp \
			Dog.cpp \
			Cat.cpp \
			WrongAnimal.cpp \
			WrongCat.cpp \
			Brain.cpp \
			utils.cpp

include ../ex00/Makefile
