# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: svogrig <svogrig@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/22 03:03:35 by svogrig           #+#    #+#              #
#    Updated: 2025/03/25 00:03:50 by svogrig          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	:=	bureaucrat

SRC 	:=	main.cpp \
			Bureaucrat.cpp \
			AForm.cpp \
			ShrubberyCreationForm.cpp \
			RobotomyRequestForm.cpp \
			PresidentialPardonForm.cpp \
			utils.cpp

include ../ex00/Makefile
